export interface Exercise {
  id: string;
  name: string;
  category: string;
  displacement: number; // in meters
}

export const defaultExercises: Exercise[] = [
  // Chest
  { id: "bench-press", name: "Bench Press", category: "Chest", displacement: 0.4 },
  { id: "incline-press", name: "Incline Press", category: "Chest", displacement: 0.4 },
  { id: "decline-press", name: "Decline Press", category: "Chest", displacement: 0.4 },
  { id: "chest-fly", name: "Chest Fly", category: "Chest", displacement: 0.5 },
  { id: "push-up", name: "Push-Up", category: "Chest", displacement: 0.4 },
  { id: "dips-chest", name: "Dips", category: "Chest", displacement: 0.4 },
  { id: "cable-crossover", name: "Cable Crossover", category: "Chest", displacement: 0.5 },
  { id: "pec-deck", name: "Pec Deck", category: "Chest", displacement: 0.4 },
  { id: "smith-machine-bench", name: "Smith Machine Bench Press", category: "Chest", displacement: 0.4 },
  { id: "chest-press-machine", name: "Chest Press Machine", category: "Chest", displacement: 0.4 },
  { id: "landmine-press-chest", name: "Landmine Press", category: "Chest", displacement: 0.5 },
  { id: "svend-press", name: "Svend Press", category: "Chest", displacement: 0.3 },
  
  // Back
  { id: "pull-up", name: "Pull-Up", category: "Back", displacement: 0.5 },
  { id: "lat-pulldown", name: "Lat Pulldown", category: "Back", displacement: 0.5 },
  { id: "bent-over-row", name: "Bent-Over Row", category: "Back", displacement: 0.5 },
  { id: "seated-row", name: "Seated Row", category: "Back", displacement: 0.5 },
  { id: "deadlift", name: "Deadlift", category: "Back", displacement: 0.6 },
  { id: "back-extension", name: "Back Extension", category: "Back", displacement: 0.4 },
  { id: "t-bar-row", name: "T-Bar Row", category: "Back", displacement: 0.5 },
  { id: "single-arm-row", name: "Single-Arm Dumbbell Row", category: "Back", displacement: 0.5 },
  { id: "face-pull-back", name: "Face Pull (Back)", category: "Back", displacement: 0.4 },
  { id: "straight-arm-pulldown", name: "Straight Arm Pulldown", category: "Back", displacement: 0.5 },
  { id: "smith-machine-row", name: "Smith Machine Row", category: "Back", displacement: 0.5 },
  { id: "lat-pullover", name: "Lat Pullover", category: "Back", displacement: 0.5 },
  { id: "meadows-row", name: "Meadows Row", category: "Back", displacement: 0.5 },
  { id: "chest-supported-row", name: "Chest Supported Row", category: "Back", displacement: 0.5 },
  
  // Legs
  { id: "squat", name: "Squat", category: "Legs", displacement: 0.6 },
  { id: "leg-press", name: "Leg Press", category: "Legs", displacement: 0.5 },
  { id: "leg-extension", name: "Leg Extension", category: "Legs", displacement: 0.5 },
  { id: "leg-curl", name: "Leg Curl", category: "Legs", displacement: 0.5 },
  { id: "calf-raise", name: "Calf Raise", category: "Legs", displacement: 0.2 },
  { id: "lunge", name: "Lunge", category: "Legs", displacement: 0.6 },
  { id: "bulgarian-split-squat", name: "Bulgarian Split Squat", category: "Legs", displacement: 0.5 },
  { id: "hack-squat", name: "Hack Squat", category: "Legs", displacement: 0.6 },
  { id: "smith-machine-squat", name: "Smith Machine Squat", category: "Legs", displacement: 0.6 },
  { id: "goblet-squat", name: "Goblet Squat", category: "Legs", displacement: 0.5 },
  { id: "sumo-squat", name: "Sumo Squat", category: "Legs", displacement: 0.6 },
  { id: "seated-calf-raise", name: "Seated Calf Raise", category: "Legs", displacement: 0.2 },
  { id: "standing-calf-raise", name: "Standing Calf Raise", category: "Legs", displacement: 0.2 },
  { id: "adductor-machine", name: "Adductor Machine", category: "Legs", displacement: 0.3 },
  { id: "abductor-machine", name: "Abductor Machine", category: "Legs", displacement: 0.3 },
  { id: "glute-bridge", name: "Glute Bridge", category: "Legs", displacement: 0.3 },
  { id: "hip-thrust", name: "Hip Thrust", category: "Legs", displacement: 0.3 },
  { id: "step-up", name: "Step Up", category: "Legs", displacement: 0.4 },
  { id: "box-jump", name: "Box Jump", category: "Legs", displacement: 0.5 },
  
  // Arms
  { id: "bicep-curl", name: "Bicep Curl", category: "Arms", displacement: 0.4 },
  { id: "hammer-curl", name: "Hammer Curl", category: "Arms", displacement: 0.4 },
  { id: "tricep-extension", name: "Tricep Extension", category: "Arms", displacement: 0.4 },
  { id: "tricep-pushdown", name: "Tricep Pushdown", category: "Arms", displacement: 0.4 },
  { id: "skull-crusher", name: "Skull Crusher", category: "Arms", displacement: 0.4 },
  { id: "wrist-curl", name: "Wrist Curl", category: "Arms", displacement: 0.2 },
  { id: "preacher-curl", name: "Preacher Curl", category: "Arms", displacement: 0.4 },
  { id: "concentration-curl", name: "Concentration Curl", category: "Arms", displacement: 0.4 },
  { id: "cable-curl", name: "Cable Curl", category: "Arms", displacement: 0.4 },
  { id: "ez-bar-curl", name: "EZ Bar Curl", category: "Arms", displacement: 0.4 },
  { id: "reverse-curl", name: "Reverse Curl", category: "Arms", displacement: 0.4 },
  { id: "overhead-tricep-extension", name: "Overhead Tricep Extension", category: "Arms", displacement: 0.5 },
  { id: "tricep-kickback", name: "Tricep Kickback", category: "Arms", displacement: 0.4 },
  { id: "diamond-push-up", name: "Diamond Push-Up", category: "Arms", displacement: 0.4 },
  { id: "close-grip-bench", name: "Close Grip Bench Press", category: "Arms", displacement: 0.4 },
  { id: "reverse-wrist-curl", name: "Reverse Wrist Curl", category: "Arms", displacement: 0.2 },
  { id: "plate-pinch", name: "Plate Pinch", category: "Arms", displacement: 0.1 },
  
  // Shoulders
  { id: "overhead-press", name: "Overhead Press", category: "Shoulders", displacement: 0.5 },
  { id: "lateral-raise", name: "Lateral Raise", category: "Shoulders", displacement: 0.5 },
  { id: "front-raise", name: "Front Raise", category: "Shoulders", displacement: 0.5 },
  { id: "rear-delt-fly", name: "Rear Delt Fly", category: "Shoulders", displacement: 0.5 },
  { id: "shrug", name: "Shrug", category: "Shoulders", displacement: 0.3 },
  { id: "upright-row", name: "Upright Row", category: "Shoulders", displacement: 0.4 },
  { id: "arnold-press", name: "Arnold Press", category: "Shoulders", displacement: 0.5 },
  { id: "push-press-shoulders", name: "Push Press", category: "Shoulders", displacement: 0.6 },
  { id: "shoulder-press-machine", name: "Shoulder Press Machine", category: "Shoulders", displacement: 0.5 },
  { id: "smith-machine-shoulder-press", name: "Smith Machine Shoulder Press", category: "Shoulders", displacement: 0.5 },
  { id: "cable-lateral-raise", name: "Cable Lateral Raise", category: "Shoulders", displacement: 0.5 },
  { id: "face-pull-shoulders", name: "Face Pull (Shoulders)", category: "Shoulders", displacement: 0.4 },
  { id: "landmine-press-shoulders", name: "Landmine Press", category: "Shoulders", displacement: 0.5 },
  { id: "bradford-press", name: "Bradford Press", category: "Shoulders", displacement: 0.5 },
  
  // Core
  { id: "crunch", name: "Crunch", category: "Core", displacement: 0.3 },
  { id: "plank", name: "Plank", category: "Core", displacement: 0.0 },
  { id: "russian-twist", name: "Russian Twist", category: "Core", displacement: 0.3 },
  { id: "leg-raise", name: "Leg Raise", category: "Core", displacement: 0.5 },
  { id: "ab-wheel", name: "Ab Wheel", category: "Core", displacement: 0.5 },
  { id: "side-bend", name: "Side Bend", category: "Core", displacement: 0.3 },
  { id: "hanging-leg-raise", name: "Hanging Leg Raise", category: "Core", displacement: 0.5 },
  { id: "mountain-climber-core", name: "Mountain Climber", category: "Core", displacement: 0.4 },
  { id: "bicycle-crunch", name: "Bicycle Crunch", category: "Core", displacement: 0.3 },
  { id: "dead-bug", name: "Dead Bug", category: "Core", displacement: 0.3 },
  { id: "hollow-hold", name: "Hollow Hold", category: "Core", displacement: 0.0 },
  { id: "v-up", name: "V-Up", category: "Core", displacement: 0.4 },
  { id: "dragon-flag", name: "Dragon Flag", category: "Core", displacement: 0.5 },
  { id: "ab-crunch-machine", name: "Ab Crunch Machine", category: "Core", displacement: 0.3 },
  { id: "cable-crunch", name: "Cable Crunch", category: "Core", displacement: 0.4 },
  { id: "oblique-crunch", name: "Oblique Crunch", category: "Core", displacement: 0.3 },
  { id: "side-plank", name: "Side Plank", category: "Core", displacement: 0.0 },
  { id: "medicine-ball-slam", name: "Medicine Ball Slam", category: "Core", displacement: 0.6 },
  
  // Cardio
  { id: "treadmill-walk-0", name: "Treadmill Walk (0% Incline)", category: "Cardio", displacement: 0.0 },
  { id: "treadmill-walk-1", name: "Treadmill Walk (1% Incline)", category: "Cardio", displacement: 0.01 },
  { id: "treadmill-walk-2", name: "Treadmill Walk (2% Incline)", category: "Cardio", displacement: 0.02 },
  { id: "treadmill-walk-3", name: "Treadmill Walk (3% Incline)", category: "Cardio", displacement: 0.03 },
  { id: "treadmill-walk-5", name: "Treadmill Walk (5% Incline)", category: "Cardio", displacement: 0.05 },
  { id: "treadmill-walk-7", name: "Treadmill Walk (7% Incline)", category: "Cardio", displacement: 0.07 },
  { id: "treadmill-walk-10", name: "Treadmill Walk (10% Incline)", category: "Cardio", displacement: 0.1 },
  { id: "treadmill-walk-12", name: "Treadmill Walk (12% Incline)", category: "Cardio", displacement: 0.12 },
  { id: "treadmill-walk-15", name: "Treadmill Walk (15% Incline)", category: "Cardio", displacement: 0.15 },
  
  { id: "treadmill-run-0", name: "Treadmill Run (0% Incline)", category: "Cardio", displacement: 0.0 },
  { id: "treadmill-run-1", name: "Treadmill Run (1% Incline)", category: "Cardio", displacement: 0.01 },
  { id: "treadmill-run-2", name: "Treadmill Run (2% Incline)", category: "Cardio", displacement: 0.02 },
  { id: "treadmill-run-3", name: "Treadmill Run (3% Incline)", category: "Cardio", displacement: 0.03 },
  { id: "treadmill-run-5", name: "Treadmill Run (5% Incline)", category: "Cardio", displacement: 0.05 },
  { id: "treadmill-run-7", name: "Treadmill Run (7% Incline)", category: "Cardio", displacement: 0.07 },
  { id: "treadmill-run-10", name: "Treadmill Run (10% Incline)", category: "Cardio", displacement: 0.1 },
  
  { id: "elliptical-low", name: "Elliptical (Low Resistance)", category: "Cardio", displacement: 0.03 },
  { id: "elliptical-medium", name: "Elliptical (Medium Resistance)", category: "Cardio", displacement: 0.05 },
  { id: "elliptical-high", name: "Elliptical (High Resistance)", category: "Cardio", displacement: 0.08 },
  
  { id: "stair-stepper-low", name: "Stair Stepper (Low Intensity)", category: "Cardio", displacement: 0.1 },
  { id: "stair-stepper-medium", name: "Stair Stepper (Medium Intensity)", category: "Cardio", displacement: 0.15 },
  { id: "stair-stepper-high", name: "Stair Stepper (High Intensity)", category: "Cardio", displacement: 0.2 },
  
  { id: "stationary-bike-low", name: "Stationary Bike (Low Resistance)", category: "Cardio", displacement: 0.02 },
  { id: "stationary-bike-medium", name: "Stationary Bike (Medium Resistance)", category: "Cardio", displacement: 0.04 },
  { id: "stationary-bike-high", name: "Stationary Bike (High Resistance)", category: "Cardio", displacement: 0.06 },
  
  { id: "rowing-machine-low", name: "Rowing Machine (Low Resistance)", category: "Cardio", displacement: 0.05 },
  { id: "rowing-machine-medium", name: "Rowing Machine (Medium Resistance)", category: "Cardio", displacement: 0.08 },
  { id: "rowing-machine-high", name: "Rowing Machine (High Resistance)", category: "Cardio", displacement: 0.12 },
  
  { id: "jump-rope", name: "Jump Rope", category: "Cardio", displacement: 0.1 },
  { id: "battle-ropes", name: "Battle Ropes", category: "Cardio", displacement: 0.05 },
  { id: "sled-push", name: "Sled Push", category: "Cardio", displacement: 0.3 },
  { id: "assault-bike", name: "Assault Bike", category: "Cardio", displacement: 0.05 },
  { id: "jacob-ladder", name: "Jacob's Ladder", category: "Cardio", displacement: 0.2 },
  
  // Full Body
  { id: "clean-and-jerk", name: "Clean and Jerk", category: "Full Body", displacement: 1.5 },
  { id: "snatch", name: "Snatch", category: "Full Body", displacement: 1.8 },
  { id: "kettlebell-swing", name: "Kettlebell Swing", category: "Full Body", displacement: 1.0 },
  { id: "burpee", name: "Burpee", category: "Full Body", displacement: 1.0 },
  { id: "thruster", name: "Thruster", category: "Full Body", displacement: 1.2 },
  { id: "turkish-get-up", name: "Turkish Get-Up", category: "Full Body", displacement: 1.5 },
  { id: "clean", name: "Clean", category: "Full Body", displacement: 1.2 },
  { id: "power-clean", name: "Power Clean", category: "Full Body", displacement: 1.2 },
  { id: "hang-clean", name: "Hang Clean", category: "Full Body", displacement: 0.9 },
  { id: "push-press-full", name: "Push Press", category: "Full Body", displacement: 0.8 },
  { id: "medicine-ball-throw", name: "Medicine Ball Throw", category: "Full Body", displacement: 1.0 },
  { id: "battle-rope-slams", name: "Battle Rope Slams", category: "Full Body", displacement: 0.8 },
  { id: "tire-flip", name: "Tire Flip", category: "Full Body", displacement: 1.0 },
  { id: "farmers-walk", name: "Farmer's Walk", category: "Full Body", displacement: 0.0 },
  { id: "bear-crawl", name: "Bear Crawl", category: "Full Body", displacement: 0.3 },
  { id: "mountain-climber-full", name: "Mountain Climber", category: "Full Body", displacement: 0.4 },
  { id: "jumping-jack", name: "Jumping Jack", category: "Full Body", displacement: 0.3 },
];